apiVersion: v1
kind: Service
metadata:
  name: {{ include "web.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "web.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "web.selectorLabels" . | nindent 4 }}
