{{- if .Values.testRunner.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.testRunner.serviceAccountName }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
{{- end }}
